CREATE TABLE IF NOT EXISTS match_idempotency (
  key TEXT PRIMARY KEY,
  userId TEXT NOT NULL,
  matchId TEXT NOT NULL,
  createdAt TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (matchId) REFERENCES matches(id) ON DELETE CASCADE
);
